
Linux:
	g++ -shared -Wl,-soname,MuSR2py.so -o MuSR2py.so -fPIC MuSR_td_PSI_bin.cpp MuSR2py.cpp

Mac:
	g++ -shared -Wl,-install_name,MuSR2py.so -o MuSR2py.so -fPIC MuSR_td_PSI_bin.cpp MuSR2py.cpp

clean:
	rm MuSR2py.so
